//#include <iostream>
//#include <exception>
//double divide(double a, double b) {
//	if(b)
//		return a / b;
//	throw std::runtime_error("division by zero");
//}
//
//int main() {
//	double num1 = 8;
//	double num2 = 0;
//	try{
//		double num3 = divide(num1, num2);
//		std::cout << num3 << std::endl;
//	}
//	catch (const std::runtime_error& e){
//		std::cout << e.what();
//	}
//	std::cout << "\nHello";
//}
